repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v4.0.0-alpha.8' # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            stages: [pre-commit]
            types_or: [css, javascript, json, html]

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v9.6.0' # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@^9.6.0
                - eslint-plugin-import@^2.29.1
                - eslint-plugin-simple-import-sort@^12.1.1
                - globals@^15.8.0
            stages: [pre-commit]

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: 'v3.2.0'
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: []
